name: Pull Request

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
        
# Cancel CI runs on a branch when new commits were pushed
# See https://stackoverflow.com/a/72408109/2582935
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: pre-commit/action@v3.0.1

  build_wheels:
    needs: [lint]
    name: PR - cp*, ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}-${{ matrix.version }}
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu, macos, windows]
        version: [latest]

    steps:
    - name: Checkout Project
      uses: actions/checkout@v3

    - name: Restore ccache
      if: runner.os != 'Windows'
      uses: actions/cache/restore@v4
      with:
        path: /tmp/ccache
        key: ccache-${{ runner.os }}-${{ github.head_ref }}-${{ github.run_id }}
        restore-keys: |
          ccache-${{ runner.os }}-${{ github.head_ref }}-
          ccache-${{ runner.os }}-

    - name: Run CIBuildWheel
      uses: pypa/cibuildwheel@v3.4.0
      env:
        CIBW_CONTAINER_ENGINE: "docker; create_args: --volume /tmp/ccache:/ccache"
        CIBW_ENVIRONMENT_LINUX: "LD_LIBRARY_PATH=/usr/local/lib64:${LD_LIBRARY_PATH} CCACHE_DIR=/ccache"
        CIBW_CONFIG_SETTINGS_LINUX: "cmake.define.CMAKE_CXX_COMPILER_LAUNCHER=ccache cmake.define.CMAKE_C_COMPILER_LAUNCHER=ccache"
        CIBW_CONFIG_SETTINGS_MACOS: "cmake.define.CMAKE_CXX_COMPILER_LAUNCHER=ccache cmake.define.CMAKE_C_COMPILER_LAUNCHER=ccache"

    - name: Save ccache
      uses: actions/cache/save@v4
      if: always() && runner.os != 'Windows'
      with:
        path: /tmp/ccache
        key: ccache-${{ runner.os }}-${{ github.head_ref }}-${{ github.run_id }}
