name: Pull Request

on:
  push:
    branches:
      - nn-macos-arm
  workflow_dispatch:

jobs:
  build_wheels:
    name: Test ARM - cp312, macOS
    runs-on: macos-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v6

    - name: Run CIBuildWheel
      uses: pypa/cibuildwheel@v3.4.0
      env:
        CIBW_CONFIG_SETTINGS_MACOS: "cmake.define.CMAKE_CXX_COMPILER_LAUNCHER=ccache cmake.define.CMAKE_C_COMPILER_LAUNCHER=ccache"
