name: Pull Request

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  build_wheels:
    name: Linux - cp*
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu]
        version: [latest]

    steps:
    - name: Checkout Project
      uses: actions/checkout@v3

    - name: Restore ccache
      uses: actions/cache/restore@v4
      with:
        path: /tmp/ccache
        key: ccache-${{ runner.os }}-${{ github.head_ref }}
        restore-keys: |
          ccache-${{ runner.os }}-${{ github.head_ref }}
          ccache-${{ runner.os }}-

    - name: Run CIBuildWheel
      uses: pypa/cibuildwheel@v3.4.0
      env:
        CIBW_CONTAINER_ENGINE: "docker; create_args: --volume /tmp/ccache:/ccache"
        CIBW_ENVIRONMENT_LINUX: "LD_LIBRARY_PATH=/usr/local/lib64:${LD_LIBRARY_PATH} CCACHE_DIR=/ccache"

    - name: Save ccache
      uses: actions/cache/save@v4
      if: always()
      with:
        path: /tmp/ccache
        key: ccache-${{ runner.os }}-${{ github.head_ref }}
